export default {
  TokenNotFound: 'Token not found.',
  InvalidToken: 'Invalid token.',
  InvalidName: 'Invalid name.',
  InvalidEmail: 'Invalid email.',
  InvalidPassword: 'Invalid password.',
  InternalServerError: 'Internal server error.',
  ErrorFindingRoutes: 'Encountered Error initializing routes from',
  MissingRequiredParameters: 'Missing required parameters.',
  FavoriteNotFound: 'Favorite not found.',
  MissingFavoriteId: 'Missing favorite Id.',
  EncodeError: 'Something went wrong while encoding password.',
  WrongPassword: 'Wrond password.',
  UserNotFound: 'User not found.',
  IdNotFound: 'Id not found.',
  Unauthorized: 'User has no permission to deal with it.',
  UserAlreadyExists: 'User already exists.',
  InvalidTitle: 'Invalid title.',
  InvalidImages: 'Images must have at least 1 item',
  InvalidItemId: 'Invalid item id.',
  InvalidPrice: 'Invalid price.',
};